[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
    "-C", "link-arg=--print-memory-usage",
    "-C", "link-arg=-Map=firmware.map",
]
runner = "picotool load -u -x -t elf"

[alias]
xtest = "test -p api --target aarch64-apple-darwin"

