//! Portable general-purpose I/O traits.
//!
//! A GPIO pin is modelled as *a thing you can write a `bool` to and read a
//! `bool` from*, plus a factory that hands out configured pins. Nothing here
//! knows what a register is; see the `pico2` crate for the RP2350
//! implementation.
//!
//! The path to a working pin: the board singleton (generated by
//! [`define_board!`](crate::define_board)) yields one [`PinHandle`] per
//! physical pin; [`Gpio::input_from_handle`] or [`Gpio::output_from_handle`]
//! consumes that handle and returns a pin configured for one mode, typed by
//! its pin number; from then on the pin is driven through [`Write`] or
//! sampled through [`Read`]. On the Pico 2 the whole sequence is:
//!
//! ```ignore
//! use api::{common::Write, gpio::Gpio};
//! use pico2::{common::board::Rp2350, gpio::gpio::Rp2350Gpio};
//!
//! let board = Rp2350::take().unwrap();
//! let mut gpio = Rp2350Gpio::new().unwrap();
//! let mut led = gpio.output_from_handle(board.pins.led).unwrap();
//! led.write(true);
//! ```
//!
//! The two `api` imports are required: a trait's methods are callable
//! only in scopes where the trait itself is imported, so leaving out
//! `use api::gpio::Gpio;` or `use api::common::Write;` turns the calls
//! above into "method not found" errors even though the driver types are in
//! scope. The complete program is `demo/src/main.rs`.

use crate::{common::{ErrorType, Read, Write}, device::PinHandle};

/// Which internal resistor, if any, holds an input pin at a known level when
/// nothing external is driving it.
///
/// An input with no pull is **floating**: its voltage is set by leakage and
/// nearby capacitive coupling, and it will read as noise — often oscillating,
/// which on an interrupt-enabled pin means a high rate of spurious level
/// transitions, each of which can trigger the interrupt. A pull
/// resistor (typically 50–100 kΩ) is weak enough that any real driver
/// overrides it, but strong enough to define the level when none does.
///
/// Choosing between [`Up`](Pull::Up) and [`Down`](Pull::Down) is determined by
/// how the external circuit is wired, not by preference:
///
/// * **Button to ground** — the switch pulls the pin low when pressed, so the
///   pin must be held high otherwise: [`Pull::Up`], and the pressed state
///   reads `false`. This is the most common arrangement, because it needs no
///   extra components and is what most breakout boards assume.
/// * **Button to VCC** (the positive supply rail) — the switch drives high
///   when pressed, so the pin must be held low otherwise: [`Pull::Down`],
///   and pressed reads `true`.
/// * **Actively driven signal** — another chip drives both levels at all
///   times, so no pull is needed: [`Pull::None`]. Use this also when an
///   external resistor is already fitted: adding an internal pull of the
///   opposite polarity would form a voltage divider with it and could leave
///   the level between the input thresholds.
///
/// Getting this backwards does not fail loudly. The pin reads a constant
/// value, or works intermittently depending on lead capacitance, which is why
/// this is a required argument rather than something with a default.
pub enum Pull {
    /// Hold the pin high when undriven. Pair with a switch to ground.
    Up,
    /// Hold the pin low when undriven. Pair with a switch to VCC.
    Down,
    /// Leave the pin floating. Only correct when something else always drives
    /// it, or an external pull resistor is fitted.
    None,
}

/// A pin configured as an input.
///
/// This is a **marker trait**: it declares no methods of its own and exists
/// to give a name to a capability. All the behaviour arrives through the
/// supertrait — an input pin is used via [`Read::read`], which samples the
/// level on the pad (the physical metal contact on the chip package that pin
/// number `N` names) as a `bool`. What the marker adds over bare `Read<bool>`
/// is the const parameter `N`, which carries the pin number in the type: a
/// function can demand *an input on pin 7* (`impl GpioPinIn<7>`) rather than
/// *something readable*.
///
/// Values implementing this come only from [`Gpio::input_from_handle`],
/// which also takes the [`Pull`] configuration — an undriven input with no
/// pull floats; see [`Pull`] for how to choose.
pub trait GpioPinIn<const N: usize>: Read<bool> {}

/// A pin configured as a push-pull output.
///
/// **Push-pull** means the pin is actively driven in both directions: one
/// transistor connects it to the supply for `true`, another to ground for
/// `false`. The contrast is an open-drain output, which only pulls low and
/// leaves the pin floating otherwise.
///
/// The output counterpart of [`GpioPinIn`], and a marker trait in the same
/// way: driving the pin happens through [`Write::write`], and `N` fixes the
/// pin number at the type level. Values implementing this come only from
/// [`Gpio::output_from_handle`].
///
/// Only `Write<bool>` is required. Reading back the level actually present
/// on an output pad is legitimate and useful — a pin shorted to ground, or
/// loaded beyond its drive strength, sits at a level other than the one
/// written, which is the cheapest fault detection available — but that is a
/// hardware capability, so a driver offers it by additionally implementing
/// [`Read<bool>`](Read) on its output type rather than by contract here.
pub trait GpioPinOut<const N: usize>: Write<bool> {}

/// The factory for configured pins: consumes a [`PinHandle`], returns a pin.
///
/// A value of an implementing type represents one GPIO **port** — the
/// hardware block that controls a group of pins — already brought out of
/// reset. Peripherals power up held in reset, an inert state from which a
/// register write must release them before they respond at all; that
/// release-and-wait sequence (**bring-up**) belongs to the implementor's
/// constructor, not to this trait. The two methods configure a single pin
/// for one mode and return a value that can do only what that mode allows.
///
/// # The associated types are *generic* associated types
///
/// An associated type — defined at [`ErrorType`], where each implementation
/// chooses one concrete `Error` — is chosen once, as a single type. A
/// **generic associated type** (GAT) is an associated type
/// that itself takes parameters — here the const parameter `N` — so an
/// implementation does not choose a single type, it chooses a *family* of
/// types indexed by pin number. The RP2350 driver picks
/// `type Output<const N: usize> = Rp2350GpioOut<N>`, so
/// `output_from_handle(board.pins.led)` returns exactly `Rp2350GpioOut<25>`.
///
/// The trait needs GATs because the pin number must survive into the
/// returned type. The chip-specific pin type uses `N` as a compile-time
/// constant (its register write compiles `1 << N` to an immediate — a
/// constant encoded directly in the instruction, needing no runtime
/// shift), and
/// keeping distinct pins as distinct types is what lets a signature say
/// which pin it expects. Without GATs the trait could name only one `Input`
/// and one `Output` type shared by every pin, and the pin number would have
/// to become a runtime field inside them.
///
/// # Consuming the handle makes double-configuration a compile error
///
/// Both methods take `handle` **by value**. [`PinHandle`] is neither `Copy`
/// nor `Clone`, so the call moves it and the moved-from place is dead: a
/// second `output_from_handle(board.pins.led)` — or an
/// `input_from_handle` of the same field elsewhere — is rejected by the
/// compiler as a use of a moved value. Configuring one pin from two places
/// is therefore not a runtime conflict to detect but a build failure. The
/// handle is zero-sized, so passing it compiles to nothing; the parameter
/// exists purely for the compiler to track.
///
/// The methods also take `&mut self`, an exclusive borrow of the port, so
/// configuration of two pins cannot interleave. On the RP2350 this prevents
/// no concrete hazard — its configuration registers are per-pin, so
/// interleaving would be harmless there — but it is part of the contract so
/// that an implementation whose port keeps shared state (say a single
/// direction register covering every pin, updated by non-atomic
/// read-modify-write) can rely on configuration calls being serialized
/// without needing a lock.
///
/// This trait's [`ErrorType`] covers construction failures. The pins it
/// returns declare their own error types — on the RP2350 the returned pins
/// are infallible (`Error = Infallible`), because everything that could fail
/// was dealt with before a pin value existed.
pub trait Gpio: ErrorType
{
    /// The input-pin type this driver returns for pin `N`.
    type Input<const N: usize>: GpioPinIn<N>;
    /// The output-pin type this driver returns for pin `N`.
    type Output<const N: usize>: GpioPinOut<N>;

    /// Configure pin `N` as an input with the given [`Pull`], consuming its
    /// handle.
    fn input_from_handle<const N: usize>(&mut self, handle: PinHandle<N>, pull: Pull) -> Result<Self::Input<N>, Self::Error>;
    /// Configure pin `N` as a push-pull output, consuming its handle. The
    /// initial output level is the implementation's choice; the RP2350
    /// driver drives low before enabling the driver, so the pin never
    /// glitches high.
    fn output_from_handle<const N: usize>(&mut self, handle: PinHandle<N>) -> Result<Self::Output<N>, Self::Error>;
}
