//! Hardware ownership, moved to compile time.
//!
//! On most embedded platforms "who owns pin 25" — or "who owns the GPIO
//! block" — is a convention: any code that can write a register can drive
//! any pin or reconfigure any peripheral, and two subsystems doing so to the
//! same hardware is a bug found at runtime, if at all. This module makes
//! that ownership a value in Rust's type system. A [`PinHandle<N>`] exists
//! for each physical pin at most once per boot, and a [`DeviceHandle<T>`]
//! exists for each peripheral type `T` at most once per boot; configuring
//! the pin or constructing the peripheral driver consumes the value; and the
//! compiler's move rules — a value that has been moved out of a binding
//! cannot be used from that binding again — turn "this hardware is already
//! in use" into a build error.
//!
//! Three pieces cooperate: [`PinHandle`], the per-pin ownership value;
//! [`DeviceHandle`], the per-peripheral ownership value; and
//! [`define_board!`](crate::define_board), the macro a chip-support crate
//! invokes to declare which pins and peripherals its board actually has and
//! to generate the one place handles are created.

use core::marker::PhantomData;

/// Ownership of physical pin `N`, as a zero-sized value.
///
/// # What a zero-sized type is
///
/// The only field is `_private: ()`, and `()` occupies zero bytes, so
/// `PinHandle<N>` occupies zero bytes. It has exactly one possible value,
/// carries no data, and compiles to nothing — moving one, storing one in a
/// struct, or passing one to a function costs zero instructions. Its entire
/// content lives in the type system: the const parameter `N` (a `usize`
/// baked into the type, so `PinHandle<25>` and `PinHandle<7>` are unrelated
/// types) and the fact that a value of the type exists at a given point in
/// the program.
///
/// # Why possession is proof
///
/// Three properties combine to make holding a `PinHandle<N>` a compile-time
/// guarantee that pin `N` exists and is owned nowhere else:
///
/// 1. **Creation is restricted.** The field is private, so code outside this
///    module cannot write `PinHandle { .. }` literally, and the only
///    constructor, [`new`](Self::new), is `unsafe`. Safe code obtains
///    handles solely from a board generated by
///    [`define_board!`](crate::define_board), whose `take` method creates
///    one handle per declared pin at most once per boot.
/// 2. **Only real pins are declared.** The macro invocation in the
///    chip-support crate lists exactly the pins wired on that board, so a
///    handle for a nonexistent pin is never created through the safe path. A
///    driver that receives a handle can rely on the pin number being valid.
/// 3. **Moves consume.** For a `Copy` type, assignment and by-value passing
///    duplicate the bits and the original binding stays usable; `Clone`
///    offers the same duplication through an explicit `.clone()` call.
///    `PinHandle` implements neither, so a function that takes it by
///    value — as
///    [`Gpio::output_from_handle`](crate::gpio::Gpio::output_from_handle)
///    does — moves it, and the compiler rejects any later use of the
///    moved-from binding.
///
/// The result: invariants that other systems check at runtime (or trust to
/// discipline) are checked by the compiler, and the check leaves no trace in
/// the binary.
pub struct PinHandle<const N: usize>
{
    _private: ()
}

impl<const N: usize> PinHandle<N>
{
    /// Create a handle without a board.
    ///
    /// This is the one public constructor that bypasses the
    /// [`define_board!`](crate::define_board) `take()` path: the
    /// exists-and-unowned obligations that path normally discharges fall
    /// entirely on the caller (see Safety).
    ///
    /// `const` so that [`define_board!`](crate::define_board)'s generated
    /// board constructor can be a `const fn`, and so a handle can in
    /// principle be created in a `static` initializer.
    ///
    /// # Safety
    ///
    /// Calling this asserts, with no compiler assistance, everything a
    /// handle normally proves: that pin `N` exists on the target hardware,
    /// and that no other `PinHandle<N>` is live anywhere in the program. Two
    /// live handles for one pin allow two owners to configure and drive the
    /// same hardware independently, which is exactly the aliasing this type
    /// exists to rule out.
    ///
    /// The intended caller is the code `define_board!` generates: it invokes
    /// this once per declared pin, and only from a path that a
    /// `compare_exchange` allows to run at most once per boot — which
    /// discharges both obligations. Call it directly only in host-side tests
    /// or on hardware not (yet) described by a `define_board!` invocation.
    pub const unsafe fn new() -> Self
    {
        Self { _private: () }
    }
}

/// Ownership of the one peripheral of type `T`, as a zero-sized value.
///
/// The peripheral-level counterpart to [`PinHandle`]: where a `PinHandle<N>`
/// is the sole claim on physical pin `N`, a `DeviceHandle<T>` is the sole
/// claim on the peripheral that the driver type `T` controls — the RP2350's
/// GPIO port, a UART, an SPI controller. A driver constructor takes the
/// handle by value, so constructing the driver consumes the claim and a
/// second construction is rejected by the compiler as use of a moved value.
/// That replaces the runtime alternative (a `static` flag per driver checked
/// in its constructor) with a check that costs nothing and fails at build
/// time.
///
/// # Why `PhantomData`
///
/// The only field is a [`PhantomData<T>`](core::marker::PhantomData):
/// a zero-sized marker that makes the type parameter `T` part of this
/// struct's type without storing a `T`. It gives `DeviceHandle` the same two
/// properties `PinHandle` gets from `_private: ()` and `const N` (see
/// [`PinHandle`]'s zero-sized-type explanation): the value occupies zero
/// bytes, and handles for different peripherals are unrelated types —
/// `DeviceHandle<Rp2350Gpio>` cannot be passed where a
/// `DeviceHandle<Rp2350Uart>` is required. One generic type in this crate
/// therefore covers every peripheral on every chip; the chip-support crate
/// never defines its own token types, it only names its driver types inside
/// the parameter.
///
/// # Why possession is proof
///
/// The same three-part argument as [`PinHandle`]: creation is restricted
/// (private field, `unsafe` constructor, safe code reaches handles only
/// through a [`define_board!`](crate::define_board) board's `take()`); only
/// peripherals the board declares get a handle; and the type is neither
/// `Copy` nor `Clone`, so the driver constructor's by-value parameter moves
/// the handle and ends the claim's availability.
pub struct DeviceHandle<T>{
    _private: PhantomData<T>,
}

impl<T> DeviceHandle<T>{
    /// Create a handle without a board.
    ///
    /// The peripheral-level twin of [`PinHandle::new`], with the same
    /// contract: this is the one public constructor that bypasses the
    /// [`define_board!`](crate::define_board) `take()` path, and the
    /// obligations that path normally discharges fall on the caller.
    ///
    /// `const` for the same reason as [`PinHandle::new`]: the generated
    /// board constructor is a `const fn`.
    ///
    /// # Safety
    ///
    /// Calling this asserts, with no compiler assistance, that no other
    /// `DeviceHandle<T>` is live anywhere in the program. Two live handles
    /// for one peripheral allow two independent driver values for the same
    /// hardware, whose register writes interleave without coordination —
    /// exactly what the handle exists to rule out. Call it directly only in
    /// host-side tests or on hardware not (yet) described by a
    /// `define_board!` invocation.
    pub const unsafe fn new() -> Self {
        Self{_private: PhantomData}
    }
}

/// Declares a board: which pins and peripherals exist, and the singleton
/// that owns them all.
///
/// A chip-support crate invokes this once with a board type name, a pins
/// type name, a `name: number` list of the pins actually wired on that
/// board, and an optional `devices` section listing one `name: DriverType`
/// entry per peripheral. The `pico2` crate declares `gpio0`–`gpio22` plus
/// semantic names (`led: 25`, `vbus_sense: 24`, ...) for the pins the
/// Pico 2 commits to on-board functions, and `gpio: Rp2350Gpio` as its
/// first device.
///
/// # What it expands to
///
/// ```ignore
/// define_board! {
///     Rp2350 {
///         Rp2350Pins {
///             gpio0: 0,
///             led: 25,
///         }
///         devices {
///             gpio: Rp2350Gpio,
///         }
///     }
/// }
/// // expands to (paths abbreviated):
/// static BOARD_TAKEN: AtomicBool = AtomicBool::new(false);
///
/// pub struct Rp2350Pins {
///     pub gpio0: PinHandle<0>,
///     pub led: PinHandle<25>,
/// }
///
/// pub struct Rp2350 {
///     pub pins: Rp2350Pins,
///     pub gpio: DeviceHandle<Rp2350Gpio>,
/// }
///
/// impl Rp2350 {
///     const fn new() -> Self { /* unsafe: creates every handle */ }
///     pub fn take() -> Option<Self> { /* first caller wins; see below */ }
/// }
/// ```
///
/// The `devices` section may be omitted; the board then holds only pins.
///
/// The structs and their fields are `pub`; the constructor that performs the
/// `unsafe` handle creation is private, so the only safe route to the
/// handles is `take()`, and each handle reaches safe code exactly once per
/// boot. `take()` returns [`Option<Self>`](Option) — an enum that is either
/// `Some(board)` or `None` — so every caller must handle the case where the
/// board was already claimed.
///
/// A device entry produces a [`DeviceHandle<T>`], not a driver value: the
/// board records that the peripheral exists and is unclaimed, and hardware
/// bring-up runs later, when the driver constructor consumes the handle
/// (`Rp2350Gpio::new(board.gpio)` releases the GPIO blocks from reset, for
/// example). Peripherals an application never claims are never brought up.
///
/// # Why a macro and not a type
///
/// Each board has a different set of pins with different names, and each
/// field needs a distinct type (`PinHandle<0>` is not `PinHandle<25>`). No
/// generic `Board<...>` type written in this crate could produce a named
/// field per pin — and this crate deliberately knows nothing about any
/// concrete chip. Generating the definition into the crate that does know
/// keeps `api` free of hardware facts while still being the sole authority
/// on how handles are created.
///
/// # Known rough edges
///
/// * The expansion names `Acquire` unqualified, so the invoking module must
///   have `use core::sync::atomic::Ordering::Acquire;` in scope.
/// * `BOARD_TAKEN` is a fixed name, so two invocations in one module collide
///   at compile time. One board per module.
#[macro_export]
macro_rules! define_board {
    (
        $board:ident{
            $pins:ident {
                $($pin_name:ident: $n:literal),+ $(,)?
            }
            $(devices {
                $($dev_name:ident: $dev_ty:ty),+ $(,)?
            })?
        }
    ) =>
    {
        /// Set to `true` by the first successful `take()`; never cleared.
        static BOARD_TAKEN:core::sync::atomic::AtomicBool = core::sync::atomic::AtomicBool::new(false);
        /// One field per pin declared in the `define_board!` invocation.
        /// Each field holds the sole `PinHandle` for its pin; moving a field
        /// out (into a GPIO factory method, say) consumes that pin's handle
        /// for the rest of the boot.
        pub struct $pins {
            $(pub $pin_name: $crate::device::PinHandle<$n>,)+
        }
        /// The board singleton. Obtain it with `take()`, exactly once per
        /// boot; the pin handles live in `pins`, and each declared device's
        /// `DeviceHandle` is a field of its own.
        pub struct $board {
            pub pins: $pins,
            $($(pub $dev_name: $crate::device::DeviceHandle<$dev_ty>,)+)?
        }

        impl $board {
            /// Create every declared handle at once.
            ///
            /// Sound only because this is private and its sole caller is
            /// `take()`, which succeeds at most once per boot — so no
            /// `PinHandle` or `DeviceHandle` is ever created twice.
            const fn new() -> Self {
                unsafe{Self{
                    pins: $pins{$($pin_name: $crate::device::PinHandle::new(), )+},
                    $($($dev_name: $crate::device::DeviceHandle::new(),)+)?
                }}
            }
            /// Claim the board, once per boot.
            ///
            /// The pin and device handles inside are zero-sized proofs of
            /// ownership, so the only invariant that needs runtime
            /// enforcement is that they are created once.
            /// This compare-exchange is that enforcement: the first caller gets the
            /// board, every later caller gets `None`.
            ///
            /// # Why `compare_exchange`, not a load followed by a store
            ///
            /// A load-then-store has a window: on a dual-core chip (the
            /// RP2350 has two Cortex-M33 cores), or with an interrupt
            /// handler running between the load and the store, two callers
            /// can both read `false` and both proceed to claim the board.
            /// `compare_exchange(false, true, ..)` is a single atomic
            /// read-modify-write — the hardware guarantees exactly one
            /// caller observes `false` and swaps in `true`; every other
            /// caller observes `true`, gets `Err`, and maps to `None`.
            ///
            /// # The memory orderings
            ///
            /// An ordering tells the compiler and the CPU how far they may
            /// reorder *other* memory operations across the atomic one.
            /// `Acquire` — given here for both the success and failure
            /// case — forbids moving later loads and stores before the
            /// atomic operation, so nothing done with the claimed board can
            /// be reordered ahead of the claim itself. Note what the
            /// ordering is *not* doing: the once-only guarantee comes from
            /// the read-modify-write being atomic and would hold even under
            /// `Relaxed`, and no prior writes need publishing to the winner,
            /// because the handles are zero-sized and `new()` stores
            /// nothing. `Acquire` is simply the conservative floor for a
            /// claim that later code depends on having happened.
            pub fn take() -> Option<Self> {
                return BOARD_TAKEN
                    .compare_exchange(false, true, Acquire, Acquire)
                    .ok()
                    .map(|_| Self::new());
            }
        }
    };
}
